---
- name: Check if k3d is installed
  ansible.builtin.command: which k3d
  register: k3d_check
  changed_when: false
  failed_when: k3d_check.rc != 0

- name: Check if mkcert is installed
  ansible.builtin.command: which mkcert
  register: mkcert_check
  changed_when: false
  failed_when: mkcert_check.rc != 0

- name: Check if tofu is installed
  ansible.builtin.command: which tofu
  register: tofu_check
  changed_when: false
  failed_when: tofu_check.rc != 0
